### ISSUE TITLE
Break up big pages

### ISSUE THREAD

**Issue by mDuo13** [XRPLF/xrpl-dev-portal#1028]
Some pages are too large, making it easy to get lost, hard to find what you want, or just causing them to load slowly.

The following is a list of candidates for potentially splitting into smaller, individually-functional pieces. They don't all necessarily need to be split up; this is just a starting point for making careful decisions about what to keep together or divide:

```
31093	./references/rippled-api/api-conventions/serialization.md
31279	./tutorials/get-started/look-up-transaction-results.md
31821	./concepts/consensus-network/consensus.ja.md
32816	./references/rippled-api/public-rippled-methods/subscription-methods/subscribe.md
32839	./tutorials/use-complex-payment-types/use-payment-channels.md
32992	./tutorials/get-started/monitor-incoming-payments-with-websocket.ja.md
33408	./tutorials/use-simple-xrp-payments/reliable-transaction-submission.md
33880	./references/rippled-api/public-rippled-methods/account-methods/account_tx.ja.md
36529	./references/rippled-api/api-conventions/serialization.ja.md
38305	./tutorials/use-complex-payment-types/use-payment-channels.ja.md
38316	./references/rippled-api/public-rippled-methods/subscription-methods/subscribe.ja.md
38429	./references/rippled-api/public-rippled-methods/transaction-methods/tx_history.ja.md
40878	./tutorials/get-started/look-up-transaction-results.ja.md
42641	./tutorials/use-simple-xrp-payments/reliable-transaction-submission.ja.md
50101	./references/rippled-api/public-rippled-methods/account-methods/account_objects.md
53714	./tutorials/xrp-ledger-businesses/become-an-xrp-ledger-gateway.md
55653	./concepts/consensus-network/amendments/known-amendments.md
62302	./concepts/consensus-network/amendments/known-amendments.ja.md
63353	./references/rippled-api/public-rippled-methods/transaction-methods/tx_history.md
219974	./references/data-api.md
252545	./references/data-api.ja.md
```

also, the RippleAPI/ripple-lib reference, but that's sourced from outside this repo.

**Comment by wardman12345** [comment]
an algorithm that synchronizes the information, in real time.

**Comment by mDuo13** [comment]
- [x] Remove Data API reference (#1052)
- [ ] Move `tx_history` example responses to an include
- [ ] Split up Gateway Guide's technical info section:
    - [ ] Disallow XRP tutorial
    - [ ] Authorized Trust Lines tutorials (related: #1054)
    - [ ] Transfer Fees (how to set up
    - [ ] "Sending Payments to Customers" → "Issuing Tokens"
- [ ] Move `account_objects` example responses to an include
- [ ] Make subpages for [subscription](https://xrpl.org/subscribe.html) message types
- [ ] Split off transaction-type-specific info in [Look Up Transaction Results' Interpret Metadata section](https://xrpl.org/look-up-transaction-results.html#2-interpret-metadata) into subpages (possibly moving under the transaction types or metadata info of the protocol reference).

For purposes of this ticket, splitting sections into their own pages is sufficient; they don't need to be updated, made interactive, etc. (That would be good, but doing it for all the stuff that needs to be broken up would make this too large a task to finish and review in a timely fashion, so updating the content should be separate tasks.) Also, splitting up the payment channels doc is to be done in #1055.

**Comment by mDuo13** [comment]
Some of this is done as of the most recent information architecture rework, and the rest can be handled on a case-by-case basis without this ticket.
