### ISSUE TITLE
Follow-up tasks for toolchain migration to Redocly

### ISSUE THREAD

**Issue by amarantha-k** [XRPLF/xrpl-dev-portal#2350]
The following tasks/issues are non-blockers and can be addressed after rolling out the Redocly-based site.
- [x] On the Code Samples page, the code samples return a 404 as the href is generating `/content/_code-samples/` instead of `/_code-samples/`.
- [x] Add osano widget for cookie preferences.
- [ ] Fix usability issues noted in https://github.com/XRPLF/xrpl-dev-portal/issues/2408
- [ ] Add/migrate Full Docs Index page
- [x] Add proper landing pages for Blog homepage, labels and others (#2360)
- [ ] Localization updates to bring parity to the translated pages
       - [ ] Port Ja pages that have already been translated and have not changed much. 
       - [ ] Improve localization in custom pages, particularly dev tools. (Currently, some strings that should be translated aren't, or are split up in ways that aren't appropriate.)
       - [ ] Fix links in Japanese pages that were previously being fixed with link substitution. (Probably to be solved by adding anchors in headers of some translated files, i.e. `<a id="#link-in-english"></a>`) 
       - [ ] In mobile view, the language picker is hidden in both the header and footer.
       - [ ] While viewing a Japanese page, all links from docs/index.page.tsx, etc. that use the href in the a tag will take the user to the English page.
- [ ]  Localization - Script to add and remove (comment out) keys from translations.yaml files in other languages from changes to English content that is targeted for i18next.
It would also be very easy to check pages if it is possible to see which pages use the key by commenting it out.
- [ ] Figure out a new way to track downloads of quickstart samples, if needed
- [ ] Make History Sharding diagram theme-aware
- [ ] Update tutorials landing with modular tutorials, better IA for tutorials in general
- [ ] Improve styles of left nav to make nesting more visible. (For example, the left nav of the current production site has vertical lines showing the nesting levels.)
- [x] Remove "next page" and "previous page" buttons from pages where they don't make sense. (#2367)
- [ ] Update screenshots in Dev Tools page
- [x] Figure out if Redocly publishes a sitemap automatically, and if not, how to set one up PR #2393 
- [x] Add/migrate XRPL-AI chatbot (Beta)

**Comment by tequdev** [comment]
~~Need to move `@i18n/ja/concepts` to `@i18n/ja/docs/concept`.~~

fixed

**Comment by tequdev** [comment]
In mobile view, language picker is hidden in both the header and footer.

**Comment by tequdev** [comment]
The `labels` on each page are not displayed.
<img width="205" alt="スクリーンショット 2024-02-28 13 29 46" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/c15c11db-e3ba-4c21-9c2e-96f58a21a1f2">

**Comment by tequdev** [comment]
When I access NavBar from a Japanese page, navigating to the English page.
This may be affecting these links.

- top-nav.yaml
<img width="393" alt="スクリーンショット 2024-02-28 15 26 12" src="https://github.com/XRPLF/xrpl-dev-portal/assets/69445828/bb6680b0-1f66-480d-8661-3f45d6574cd6">

**Comment by tequdev** [comment]
While viewing a Japanese page, all links from docs/index.page.tsx, etc. that use the href in the a tag will take the user to the English page.
